# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-strapi

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: /assets/images/icon.png

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Events
  url: /events/
- title: Products
  url: /products/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
# collections:
  # posts:
  #   title: Posts
  #   output: true
  #   description: "My thoughts and ideas"
  #   # feature_text: |
  #   #   Welcome to my blog
  #   feature_image: /assets/images/blog.jpg

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

strapi:
  # Your API endpoint (optional, default to http://localhost:1337)
  endpoint: http://ec2-13-245-206-239.af-south-1.compute.amazonaws.com:1337
  collections:
    posts:
      type: posts
      permalink: /posts/:title/
      layout: post.html
      output: true
    aboutmes:
      type: aboutmes
    homes:
      type: homes
    products:
      type: products
    events:
      type: events
